version: '3.1'
services: 
  nginx:
    build: 
      context: ./nginx
    container_name: 'challenge_nginx'
    restart: always
    volumes:
      - ./api:/var/www
    ports: 
      - 8000:80
    depends_on: 
      - api
      - mysql
      - redis
  api: 
    build: 
      context: ./api
    container_name: 'challence_api_fpm'
    restart: always
    environment:
      APP_KEY: 'base64:gYpC2JBb5eza5a9h4ZrV644Xk8v3t+TSoqS8jw9lLh0='
      APP_URL: 'http://localhost:8000'
      DB_HOST: 'mysql'
      DB_DATABASE: 'laravel'
      DB_USERNAME: 'root'
      DB_PASSWORD: 'example'
      CACHE_DRIVER: 'redis'
      REDIS_CLIENT: predis
      REDIS_HOST: redis
    volumes: 
      - ./api:/var/www
    depends_on: 
      - mysql
      - redis
  mysql:
    image: mysql:8
    command: '--default-authentication-plugin=mysql_native_password'
    container_name: 'challenge_mysql'
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: laravel
  adminer:
    image: adminer
    container_name: 'challenge_adminer'
    restart: always
    ports:
      - 8080:8080
  redis: 
    image: redis:alpine
    container_name: 'challenge_redis'
    restart: always
volumes:
  data:
    driver: local